"use client";
import { useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";

type FormState = "idle" | "submitting" | "success" | "error";
export function TestRideForm() {
  const [state,setState] = useState<FormState>("idle"); const [message,setMessage] = useState("");
  async function submit(formData: FormData) {
    setState("submitting"); setMessage("");
    try { const response = await fetch("/api/test-ride",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(formData.entries()))}); const data = await response.json() as {message?:string}; if(!response.ok) throw new Error(data.message||"Unable to send your request."); setState("success"); setMessage(data.message||"Your test-ride request has been received."); }
    catch(error){ setState("error"); setMessage(error instanceof Error?error.message:"We couldn't submit your request right now. Please try again."); }
  }
  if(state==="success") return <div className="form-shell success-panel" aria-live="polite"><CheckCircle2 size={34}/><p className="eyebrow">Request received</p><h3>Thank you.</h3><p>{message}</p><button type="button" onClick={()=>setState("idle")}>Send another request</button></div>;
  return <form className="form-shell" action={submit}><div className="form-heading"><span>Test-ride request</span><span>Required fields are marked *</span></div><div className="field"><label htmlFor="name">Full name *</label><input id="name" name="name" required minLength={2} maxLength={80} autoComplete="name" placeholder="Your full name"/></div><div className="field"><label htmlFor="phone">Phone number *</label><input id="phone" name="phone" required minLength={7} maxLength={24} autoComplete="tel" inputMode="tel" placeholder="e.g. +92 300 1234567"/></div><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" maxLength={120} autoComplete="email" placeholder="you@example.com"/></div><div className="field"><label htmlFor="city">City *</label><input id="city" name="city" required minLength={2} maxLength={60} autoComplete="address-level2" placeholder="Your city"/></div><div className="field field-wide"><label htmlFor="contactMethod">Preferred contact method *</label><select id="contactMethod" name="contactMethod" defaultValue="" required><option value="" disabled>Select one</option><option value="phone">Phone call</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option></select></div><div className="field field-wide"><label htmlFor="message">Message</label><textarea id="message" name="message" maxLength={500} rows={3} placeholder="Anything you would like the team to know?"/></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><label className="consent"><input type="checkbox" name="consent" value="true" required/><span>I agree to be contacted by XBOT EV regarding this request.</span></label>{message&&<p className="form-error" role="alert">{message}</p>}<button className="submit-button" type="submit" disabled={state==="submitting"}><span>{state==="submitting"?"Sending request…":"Send test-ride request"}</span><ArrowRight size={18}/></button></form>;
}
